name: Bug Report
description: Report a bug in the system
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report  
        Please fill out the details below to help us diagnose and fix the issue efficiently.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a clear and concise description of the issue."
      placeholder: "Example: When I click the 'Save' button on the settings page, nothing happens."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide the steps to reproduce this issue."
      placeholder: |
        1. Go to 'http://localhost:3000/settings'
        2. Click the 'Save' button
        3. Observe that no changes are saved
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Example: The 'Save' button should update user settings and show a success message."

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened instead?"
      placeholder: "Example: The button does nothing, and there are no error messages."

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Provide details about the environment where the issue occurred."
      placeholder: |
        - OS: Windows 11 / macOS Ventura / Ubuntu 22.04
        - Browser: Chrome 120.0.0 / Firefox 105
        - Device: iPhone 14 / Windows PC
        - Version: v1.2.3

  - type: textarea
    id: logs
    attributes:
      label: "Logs & Console Errors"
      description: "Paste any relevant logs, error messages, or stack traces."
      placeholder: |
        Example:
        ```
        Uncaught TypeError: Cannot read properties of undefined
        at settings.js:45
        ```

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or Videos (Optional)"
      description: "Attach screenshots or videos that show the issue."
      placeholder: "Example: Drag and drop images or paste a link to a screen recording."
