name: New Feature
description: Suggest or request a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a clear and concise description of what this feature request is about."
      placeholder: "Example: Add a caching mechanism to improve API response time by reducing redundant database queries."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Design References"
      description: "Attach mockups, wireframes, or design references to illustrate the proposed feature."
      placeholder: "Example: Attach a Figma link or wireframe image showing how the feature should look."

  - type: textarea
    id: files
    attributes:
      label: "Relevant Files"
      description: "List key files related to this feature to help contributors navigate the project."
      placeholder: "Example: `src/api/userService.js`, `src/database/migrations/20240214_add_users_table.sql`"

  - type: textarea
    id: tasks
    attributes:
      label: "Tasks"
      description: "Break down this issue into actionable development tasks."
      placeholder: |
        - [ ] Implement API endpoint at `GET /api/v1/reports`
        - [ ] Add unit tests in `tests/ReportsTest.php`
        - [ ] Update frontend component `ReportTable.vue` to display new data"
